compile: 
	g++ exercise3.cpp adjacencylist.cpp community.cpp directed_adjacencylist.cpp heap.cpp jackcomesback.cpp

amazon:
	./a.out ../../Graphs/com-amazon.ungraph.txt

test:
	./a.out ../../Graphs/graph2.txt

slowest:
	./a.out ../../Graphs/com-lj.ungraph.txt

